export const LOAD_CONFIG_DATA = "LOAD_CONFIG_DATA";
export const SET_ACTIVE_ORDERS = "SET_ACTIVE_ORDERS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
